### ISSUE TITLE
Epic: Extract OpenRewrite parser

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#844]
### What needs to be done
The parsing logic to create the OpenRewrite AST from given resources should be extracted.
The currently used `MavenProjectParser` should then be replaced by this component.

### Why it needs to be done
Parsing a given project to OpenRewrite AST is a mandatory step to apply OpenRewrite recipes.
Currently, two open-sourced build tool plugins exist that allow applying recipes inside a build.
Providing a parser that creates the AST outside of a build tool plugin is required for other projects too.
Extracting the parser allows reusing this component in these projects.

- [x] #832 
  - [x] Adhere to `.mvn/maven.config` ([`MavenConfigFileParserTest`](https://github.com/spring-projects-experimental/spring-boot-migrator/blob/6f5d868151309616f885c9d6f19252335f771e3f/sbm-support-rewrite/src/test/java/org/springframework/sbm/parsers/MavenConfigFileParserTest.java))
  - [ ] Adhere to `~/.m2/settings-security.xml` and `~/.m2/settings.xml` 
  - [ ] Publish parsing events registered through the `ExecutionContext` as Spring application events 
- [ ] Make `PomCache` configurable through properties
- [ ] #849
- [ ] All markers should be added exactly as if the project would have been parsed with the build tool plugins
- [ ] The ExecutionContext should be made available as scoped bean, reusing #792 and #800 
- [ ] The component should be configurable through Spring properties
  - [ ] A `rewrite.yaml` should read and the settings should be taken
- [ ] Exception handling should be configurable
  - [ ] When to throw and when to log
  - [ ] how to communicate exceptions (print in resource, collect, ...)
- [ ] Build information (ordered list of build files, dependencies for modules, and other) can be provided
- [ ] Accept OpenRewrite styles
- [ ] Allow different pom and artifact caches

### Acceptance Criteria

/info panel
**Given** precondition
**When** action
**Then** result

**Comment by shresthaujjwal** [comment]
@fabapp2 any idea when the support for custom maven settings.xml support would be added ? `Adhere to ~/.m2/settings-security.xml and ~/.m2/settings.xml`

**Comment by fabapp2** [comment]
Hi @shresthaujjwal 

it should be working with the current parser used in isolation when using RewriteMavenProjectParser which replicates works as with the rewrite-maven-plugin.
It needs to be incorporated into the RewriteProjectParser and can be taken fron [here](https://github.com/spring-projects-experimental/spring-boot-migrator/blob/771-upgrade-to-latest-openrewrite-7402/components/sbm-core/src/test/java/org/springframework/sbm/project/parser/RewriteMavenSettingsInitialierTest.java). I will find or create an issue for this.
